### ISSUE TITLE
Forge NoSuchMethodError when trying to load mod

### ISSUE THREAD

**Issue by hypothermic** [hypothermic/BTCS#1]
Example stacktrace with ComputerCraft:
```02:55:13 [SEVERE] Unexpected exception
java.lang.NoSuchMethodError: net.minecraft.server.Item.<init>(I)V
	at dan200.computer.shared.ItemDisk.<init>(ItemDisk.java:16)
	at net.minecraft.server.mod_ComputerCraft.<init>(mod_ComputerCraft.java:96)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at cpw.mods.fml.common.modloader.ModLoaderModContainer.preInit(ModLoaderModContainer.java:107)
	at cpw.mods.fml.common.Loader.preModInit(Loader.java:201)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:552)
	at cpw.mods.fml.server.FMLBukkitHandler.onPreLoad(FMLBukkitHandler.java:81)
	at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:124)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:434)
	at net.minecraft.server.ThreadServerApplication.run(ThreadServerApplication.java:14)
```
Balkon's Weapon Mod had a very similar error and I fixed it by putting all the decompiled java files into the `net.minecraft.server` package.

**Comment by hypothermic** [comment]
This issue is fixed in BTCS+
